export interface Recipe {
  id: number;
  name: string;
  description: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  rating: number;
  prepTime: string;
  servings: number;
  image: string;
  category: string;
  tags: string[];
  ingredients: string[];
  instructions: string[];
  author?: string;
  isUserSubmitted?: boolean;
}

export const recipes: Recipe[] = [
  {
    id: 1,
    name: "Mediterranean Quinoa Bowl",
    description: "A healthy and colorful bowl packed with fresh vegetables, quinoa, feta cheese, and a tangy tahini dressing",
    difficulty: "Easy",
    rating: 4.9,
    prepTime: "15 min",
    servings: 4,
    image: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600&h=400",
    category: "Healthy",
    tags: ["healthy", "vegetarian", "quinoa", "mediterranean", "quick"],
    ingredients: [
      "1 cup quinoa",
      "2 cups vegetable broth",
      "1 cucumber, diced",
      "2 cups cherry tomatoes, halved",
      "1/2 red onion, thinly sliced",
      "1/2 cup kalamata olives, pitted",
      "200g feta cheese, crumbled",
      "1/4 cup fresh parsley, chopped",
      "2 tbsp tahini",
      "2 tbsp lemon juice",
      "3 tbsp olive oil",
      "1 clove garlic, minced",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Rinse quinoa under cold water until water runs clear. In a medium saucepan, bring vegetable broth to a boil.",
      "Add quinoa to boiling broth, reduce heat to low, cover and simmer for 15 minutes until liquid is absorbed.",
      "Remove from heat and let stand 5 minutes. Fluff with a fork and let cool completely.",
      "While quinoa cools, prepare vegetables: dice cucumber, halve cherry tomatoes, and thinly slice red onion.",
      "For the dressing, whisk together tahini, lemon juice, olive oil, minced garlic, salt and pepper in a small bowl.",
      "In a large bowl, combine cooled quinoa, cucumber, tomatoes, red onion, and olives.",
      "Drizzle with tahini dressing and toss gently to combine.",
      "Top with crumbled feta cheese and fresh parsley. Serve immediately or chill for 30 minutes before serving."
    ]
  },
  {
    id: 2,
    name: "Artisan Sourdough Pizza",
    description: "Homemade sourdough pizza with San Marzano tomatoes, fresh mozzarella, and aromatic basil leaves",
    difficulty: "Medium",
    rating: 4.8,
    prepTime: "45 min",
    servings: 2,
    image: "https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&w=600&h=400",
    category: "Italian",
    tags: ["pizza", "italian", "sourdough", "homemade", "cheese"],
    ingredients: [
      "200g sourdough starter (active)",
      "300g bread flour",
      "200ml warm water",
      "1 tsp salt",
      "2 tbsp olive oil",
      "400g can San Marzano tomatoes",
      "2 cloves garlic, minced",
      "250g fresh mozzarella, torn",
      "Fresh basil leaves",
      "Extra virgin olive oil for drizzling",
      "Sea salt and black pepper"
    ],
    instructions: [
      "In a large bowl, mix sourdough starter with warm water until well combined.",
      "Add flour and salt, mix until a shaggy dough forms. Add olive oil and knead for 8-10 minutes until smooth.",
      "Place dough in oiled bowl, cover and let rise for 2-3 hours until doubled in size.",
      "Meanwhile, crush San Marzano tomatoes by hand, mix with minced garlic, salt, and pepper. Set aside.",
      "Preheat oven to maximum temperature (usually 250°C/480°F) with pizza stone or baking sheet inside.",
      "Divide dough in half. On floured surface, stretch each piece into 10-inch circles, leaving edges slightly thicker.",
      "Transfer to parchment paper. Spread thin layer of tomato sauce, leaving 1-inch border for crust.",
      "Add torn mozzarella pieces evenly across pizza. Drizzle lightly with olive oil.",
      "Slide pizza (on parchment) onto hot stone/sheet. Bake 12-15 minutes until crust is golden and cheese bubbles.",
      "Remove from oven, immediately top with fresh basil leaves and a drizzle of extra virgin olive oil. Slice and serve hot."
    ]
  },
  {
    id: 3,
    name: "Truffle Risotto",
    description: "Creamy Arborio rice slowly cooked with black truffle, parmesan cheese, and wild mushrooms",
    difficulty: "Hard",
    rating: 4.9,
    prepTime: "35 min",
    servings: 4,
    image: "https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600&h=400",
    category: "Gourmet",
    tags: ["risotto", "truffle", "gourmet", "italian", "mushrooms", "rice"],
    ingredients: [
      "320g Arborio rice",
      "1.2L warm chicken or vegetable stock",
      "1 medium onion, finely chopped",
      "2 cloves garlic, minced",
      "150ml dry white wine",
      "200g mixed wild mushrooms, sliced",
      "50g butter",
      "100g Parmigiano-Reggiano, grated",
      "30g black truffle, thinly shaved",
      "2 tbsp truffle oil",
      "3 tbsp olive oil",
      "Salt and white pepper to taste",
      "Fresh parsley for garnish"
    ],
    instructions: [
      "Heat stock in a saucepan and keep warm on low heat throughout cooking process.",
      "In a large, heavy-bottomed pan, heat olive oil over medium heat. Sauté mushrooms until golden, season and set aside.",
      "In the same pan, add half the butter. Sauté onion until translucent, about 3-4 minutes.",
      "Add garlic and cook for 1 minute. Add Arborio rice, stirring constantly for 2 minutes until grains are coated.",
      "Pour in white wine, stirring until completely absorbed by the rice.",
      "Add warm stock one ladle at a time, stirring constantly. Wait until each addition is absorbed before adding more.",
      "Continue this process for 18-20 minutes until rice is creamy but still has slight bite (al dente).",
      "In the last 5 minutes, fold in the sautéed mushrooms.",
      "Remove from heat. Stir in remaining butter, grated Parmigiano-Reggiano, and truffle oil.",
      "Season with salt and white pepper. Serve immediately topped with shaved black truffle and fresh parsley."
    ]
  },
  {
    id: 4,
    name: "Herb-Crusted Salmon",
    description: "Fresh Atlantic salmon with a crispy herb crust, served with roasted vegetables and lemon sauce",
    difficulty: "Medium",
    rating: 4.7,
    prepTime: "25 min",
    servings: 4,
    image: "https://images.pexels.com/photos/1640775/pexels-photo-1640775.jpeg?auto=compress&cs=tinysrgb&w=600&h=400",
    category: "Seafood",
    tags: ["salmon", "seafood", "herbs", "healthy", "fish", "protein"],
    ingredients: [
      "4 salmon fillets (150g each), skin removed",
      "1 cup fresh breadcrumbs",
      "3 tbsp fresh parsley, chopped",
      "2 tbsp fresh dill, chopped",
      "1 tbsp fresh chives, chopped",
      "2 cloves garlic, minced",
      "3 tbsp olive oil",
      "1 lemon (zested and juiced)",
      "2 tbsp Dijon mustard",
      "400g baby potatoes, halved",
      "200g asparagus, trimmed",
      "1 red bell pepper, sliced",
      "Salt and black pepper to taste"
    ],
    instructions: [
      "Preheat oven to 200°C (400°F). Line a large baking sheet with parchment paper.",
      "Toss halved potatoes with 1 tbsp olive oil, salt, and pepper. Roast for 15 minutes.",
      "Meanwhile, combine breadcrumbs, parsley, dill, chives, garlic, lemon zest, and 2 tbsp olive oil in a bowl.",
      "Pat salmon fillets dry and season with salt and pepper. Brush tops with Dijon mustard.",
      "Press herb breadcrumb mixture firmly onto mustard-coated salmon fillets.",
      "Add asparagus and bell pepper to the baking sheet with potatoes. Drizzle with remaining oil.",
      "Place herb-crusted salmon on the same baking sheet. Bake for 12-15 minutes until salmon flakes easily.",
      "For lemon sauce: whisk together lemon juice, 2 tbsp olive oil, salt, and pepper.",
      "Remove from oven and let rest 2 minutes. Serve salmon with roasted vegetables and lemon sauce drizzled over."
    ]
  },
  {
    id: 5,
    name: "Chocolate Lava Cake",
    description: "Decadent individual chocolate cakes with a molten center, served with vanilla ice cream",
    difficulty: "Medium",
    rating: 4.9,
    prepTime: "20 min",
    servings: 6,
    image: "https://images.pexels.com/photos/1640778/pexels-photo-1640778.jpeg?auto=compress&cs=tinysrgb&w=600&h=400",
    category: "Dessert",
    tags: ["chocolate", "dessert", "cake", "sweet", "molten", "indulgent"],
    ingredients: [
      "200g dark chocolate (70% cocoa), chopped",
      "200g unsalted butter",
      "4 large eggs",
      "4 large egg yolks",
      "100g caster sugar",
      "60g plain flour",
      "1 tsp vanilla extract",
      "Pinch of salt",
      "Butter for ramekins",
      "Cocoa powder for dusting",
      "Vanilla ice cream for serving",
      "Fresh berries for garnish",
      "Powdered sugar for dusting"
    ],
    instructions: [
      "Preheat oven to 220°C (425°F). Generously butter six 150ml ramekins and dust with cocoa powder.",
      "Place chocolate and butter in a double boiler or microwave-safe bowl. Melt gently, stirring until smooth.",
      "In a separate bowl, whisk whole eggs, egg yolks, and sugar vigorously for 2-3 minutes until pale and thick.",
      "Slowly pour melted chocolate mixture into egg mixture, whisking constantly to prevent eggs from cooking.",
      "Add vanilla extract and salt, then gently fold in flour until just combined. Don't overmix.",
      "Divide batter evenly among prepared ramekins, filling each about 3/4 full.",
      "Place ramekins on a baking tray and bake for 12-14 minutes until edges are firm but centers still jiggle slightly.",
      "Remove from oven and let cool for exactly 1 minute - no longer or centers will set.",
      "Run a knife around edges to loosen, then quickly invert each ramekin onto serving plates.",
      "Dust with powdered sugar, add a scoop of vanilla ice cream and fresh berries. Serve immediately while centers are molten."
    ]
  },
  {
    id: 6,
    name: "Garden Fresh Salad",
    description: "Seasonal mixed greens with cherry tomatoes, cucumber, and homemade herb vinaigrette",
    difficulty: "Easy",
    rating: 4.6,
    prepTime: "10 min",
    servings: 4,
    image: "https://images.pexels.com/photos/1640776/pexels-photo-1640776.jpeg?auto=compress&cs=tinysrgb&w=600&h=400",
    category: "Healthy",
    tags: ["salad", "healthy", "fresh", "vegetables", "light", "quick"],
    ingredients: [
      "150g mixed salad greens (arugula, spinach, lettuce)",
      "200g cherry tomatoes, halved",
      "1 large cucumber, sliced",
      "1/2 red onion, thinly sliced",
      "1 avocado, sliced",
      "100g feta cheese, crumbled",
      "1/4 cup sunflower seeds",
      "3 tbsp extra virgin olive oil",
      "1 tbsp balsamic vinegar",
      "1 tsp Dijon mustard",
      "1 tsp honey",
      "2 tbsp fresh herbs (basil, parsley, chives)",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Wash and thoroughly dry all salad greens. Tear larger leaves into bite-sized pieces.",
      "Prepare vegetables: halve cherry tomatoes, slice cucumber and red onion, and slice avocado just before serving.",
      "For the vinaigrette: In a small bowl, whisk together Dijon mustard and honey until smooth.",
      "Slowly add balsamic vinegar while whisking, then gradually drizzle in olive oil, whisking constantly until emulsified.",
      "Stir in chopped fresh herbs and season with salt and pepper to taste.",
      "In a large salad bowl, combine mixed greens, cherry tomatoes, cucumber, and red onion.",
      "Drizzle with half the vinaigrette and toss gently to coat all ingredients evenly.",
      "Add sliced avocado and crumbled feta cheese on top.",
      "Sprinkle with sunflower seeds and drizzle with remaining vinaigrette if desired. Serve immediately."
    ]
  },
  {
    id: 7,
    name: "Thai Green Curry",
    description: "Aromatic Thai curry with coconut milk, fresh vegetables, and fragrant herbs",
    difficulty: "Medium",
    rating: 4.8,
    prepTime: "30 min",
    servings: 4,
    image: "https://images.pexels.com/photos/2347311/pexels-photo-2347311.jpeg?auto=compress&cs=tinysrgb&w=600&h=400",
    category: "Asian",
    tags: ["thai", "curry", "coconut", "spicy", "vegetables", "asian"],
    ingredients: [
      "3 tbsp green curry paste",
      "400ml coconut milk",
      "200ml chicken stock",
      "500g chicken thigh, cut into strips",
      "2 Thai eggplants, quartered",
      "1 red bell pepper, sliced",
      "100g green beans, trimmed",
      "2 tbsp fish sauce",
      "1 tbsp palm sugar (or brown sugar)",
      "4 kaffir lime leaves, torn",
      "2 Thai chilies, sliced",
      "1 cup Thai basil leaves",
      "2 tbsp vegetable oil",
      "Jasmine rice for serving",
      "Lime wedges for garnish"
    ],
    instructions: [
      "Heat oil in a large wok or deep pan over medium-high heat.",
      "Add green curry paste and fry for 2-3 minutes until fragrant, stirring constantly to prevent burning.",
      "Pour in thick part of coconut milk (from top of can) and stir to combine with curry paste.",
      "Add chicken strips and cook for 5-6 minutes until chicken changes color and is nearly cooked through.",
      "Add remaining coconut milk and chicken stock. Bring to a gentle simmer.",
      "Add eggplant pieces and simmer for 5 minutes until they start to soften.",
      "Add bell pepper and green beans. Cook for 3-4 minutes until vegetables are tender-crisp.",
      "Season with fish sauce and palm sugar. Add torn kaffir lime leaves and Thai chilies.",
      "Simmer for 2-3 more minutes to allow flavors to meld. Taste and adjust seasoning.",
      "Remove from heat and stir in fresh Thai basil leaves. Serve immediately over jasmine rice with lime wedges."
    ]
  },
  {
    id: 8,
    name: "French Onion Soup",
    description: "Classic French soup with caramelized onions, rich beef broth, and melted Gruyère cheese",
    difficulty: "Medium",
    rating: 4.7,
    prepTime: "60 min",
    servings: 6,
    image: "https://images.pexels.com/photos/539451/pexels-photo-539451.jpeg?auto=compress&cs=tinysrgb&w=600&h=400",
    category: "French",
    tags: ["french", "soup", "onions", "cheese", "comfort", "classic"],
    ingredients: [
      "6 large yellow onions, thinly sliced",
      "4 tbsp butter",
      "2 tbsp olive oil",
      "1 tsp sugar",
      "1 tsp salt",
      "1/2 cup dry white wine",
      "1.5L rich beef stock",
      "2 bay leaves",
      "4 fresh thyme sprigs",
      "1/2 tsp black pepper",
      "6 thick slices French bread",
      "200g Gruyère cheese, grated",
      "50g Parmesan cheese, grated",
      "2 tbsp fresh chives, chopped"
    ],
    instructions: [
      "In a large, heavy-bottomed pot, melt butter with olive oil over medium heat.",
      "Add sliced onions, sugar, and salt. Cook, stirring occasionally, for 45-60 minutes until deep golden brown and caramelized.",
      "The onions should be very soft and jammy. If they brown too quickly, reduce heat and add a splash of water.",
      "Add white wine to deglaze the pot, scraping up any browned bits from the bottom.",
      "Pour in beef stock, add bay leaves and thyme sprigs. Bring to a boil, then reduce heat and simmer for 20 minutes.",
      "Season with black pepper and adjust salt to taste. Remove bay leaves and thyme stems.",
      "Preheat oven broiler. Toast bread slices until golden on both sides.",
      "Ladle soup into oven-safe bowls. Float one piece of toasted bread on each serving.",
      "Generously top each bowl with grated Gruyère and Parmesan cheese.",
      "Place bowls on a baking sheet and broil for 2-4 minutes until cheese is bubbly and golden. Garnish with chives and serve immediately."
    ]
  },
  {
    id: 9,
    name: "Beef Tacos",
    description: "Authentic Mexican tacos with seasoned ground beef, fresh salsa, and traditional toppings",
    difficulty: "Easy",
    rating: 4.6,
    prepTime: "20 min",
    servings: 4,
    image: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&cs=tinysrgb&w=600&h=400",
    category: "Mexican",
    tags: ["tacos", "mexican", "beef", "quick", "family", "spicy"],
    ingredients: [
      "500g ground beef (80/20 blend)",
      "8 corn tortillas",
      "1 medium onion, diced",
      "3 cloves garlic, minced",
      "2 tsp chili powder",
      "1 tsp ground cumin",
      "1 tsp paprika",
      "1/2 tsp oregano",
      "1/4 tsp cayenne pepper",
      "Salt and black pepper",
      "2 tomatoes, diced",
      "1/2 white onion, finely diced",
      "1 jalapeño, minced",
      "1/4 cup cilantro, chopped",
      "2 limes, juiced",
      "200g Mexican cheese, shredded",
      "1 cup lettuce, shredded",
      "Sour cream for serving"
    ],
    instructions: [
      "For the salsa: combine diced tomatoes, white onion, jalapeño, cilantro, and lime juice in a bowl. Season with salt and set aside.",
      "Heat a large skillet over medium-high heat. Add ground beef and diced onion.",
      "Cook, breaking up meat with a spoon, for 6-8 minutes until beef is browned and onion is softened.",
      "Add minced garlic and cook for 1 minute until fragrant.",
      "Add all spices (chili powder, cumin, paprika, oregano, cayenne) and season with salt and pepper.",
      "Cook for 2-3 minutes, stirring constantly, until spices are fragrant and meat is well-coated.",
      "Add 1/4 cup water if mixture seems dry. Simmer for 2 minutes, then remove from heat.",
      "Warm tortillas in a dry skillet for 30 seconds per side, or wrap in damp paper towels and microwave for 30 seconds.",
      "To assemble: place warm tortillas on plates, add seasoned beef down the center of each.",
      "Top with fresh salsa, shredded cheese, lettuce, and a dollop of sour cream. Serve with lime wedges."
    ]
  },
  {
    id: 10,
    name: "Mushroom Stroganoff",
    description: "Creamy vegetarian stroganoff with mixed mushrooms, served over egg noodles",
    difficulty: "Easy",
    rating: 4.5,
    prepTime: "25 min",
    servings: 4,
    image: "https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg?auto=compress&cs=tinysrgb&w=600&h=400",
    category: "Vegetarian",
    tags: ["vegetarian", "mushrooms", "creamy", "comfort", "pasta", "easy"],
    ingredients: [
      "400g wide egg noodles",
      "500g mixed mushrooms (button, cremini, shiitake), sliced",
      "1 large onion, sliced",
      "3 cloves garlic, minced",
      "3 tbsp butter",
      "2 tbsp olive oil",
      "3 tbsp plain flour",
      "500ml vegetable stock",
      "200ml sour cream",
      "2 tbsp Dijon mustard",
      "2 tbsp Worcestershire sauce",
      "1/4 cup fresh parsley, chopped",
      "Salt and black pepper to taste",
      "Paprika for garnish"
    ],
    instructions: [
      "Cook egg noodles according to package directions until al dente. Drain and set aside.",
      "Heat olive oil in a large skillet over medium-high heat. Add sliced mushrooms in a single layer.",
      "Cook mushrooms without stirring for 4-5 minutes until golden brown on one side, then stir and cook 3 more minutes.",
      "Remove mushrooms from pan and set aside. In the same pan, melt butter over medium heat.",
      "Add sliced onion and cook for 5-6 minutes until softened and lightly caramelized.",
      "Add minced garlic and cook for 1 minute until fragrant.",
      "Sprinkle flour over onions and stir constantly for 2 minutes to cook out raw flour taste.",
      "Gradually whisk in vegetable stock, ensuring no lumps form. Bring to a simmer.",
      "Stir in Dijon mustard and Worcestershire sauce. Return mushrooms to the pan.",
      "Simmer for 5 minutes until sauce thickens. Remove from heat and stir in sour cream and parsley.",
      "Season with salt and pepper. Serve over egg noodles, garnished with paprika and extra parsley."
    ]
  },
  {
    id: 11,
    name: "Lemon Garlic Shrimp",
    description: "Quick and flavorful shrimp sautéed with garlic, lemon, and fresh herbs",
    difficulty: "Easy",
    rating: 4.8,
    prepTime: "12 min",
    servings: 4,
    image: "https://images.pexels.com/photos/725991/pexels-photo-725991.jpeg?auto=compress&cs=tinysrgb&w=600&h=400",
    category: "Seafood",
    tags: ["shrimp", "seafood", "garlic", "lemon", "quick", "light"],
    ingredients: [
      "600g large shrimp, peeled and deveined",
      "6 cloves garlic, minced",
      "1/4 cup olive oil",
      "3 tbsp butter",
      "1/4 cup dry white wine",
      "2 lemons (juiced and zested)",
      "1/4 cup fresh parsley, chopped",
      "1/4 tsp red pepper flakes",
      "Salt and black pepper to taste",
      "Cooked pasta or rice for serving",
      "Lemon wedges for garnish"
    ],
    instructions: [
      "Pat shrimp completely dry with paper towels. Season generously with salt and pepper.",
      "Heat olive oil in a large skillet over medium-high heat until shimmering.",
      "Add shrimp in a single layer, don't overcrowd. Cook for 1-2 minutes until pink on one side.",
      "Flip shrimp and cook for another 1-2 minutes until pink and cooked through. Remove shrimp to a plate.",
      "Reduce heat to medium and add butter to the same pan.",
      "Add minced garlic and red pepper flakes. Sauté for 30 seconds until fragrant, don't let garlic brown.",
      "Pour in white wine to deglaze the pan, scraping up any browned bits.",
      "Add lemon juice and zest. Let the sauce simmer for 1-2 minutes to reduce slightly.",
      "Return shrimp to the pan and toss to coat with the lemon garlic sauce.",
      "Remove from heat and stir in fresh parsley. Taste and adjust seasoning.",
      "Serve immediately over pasta or rice, garnished with lemon wedges and extra parsley."
    ]
  },
  {
    id: 12,
    name: "Apple Cinnamon Pancakes",
    description: "Fluffy pancakes with caramelized apples and warm cinnamon spice",
    difficulty: "Easy",
    rating: 4.7,
    prepTime: "20 min",
    servings: 4,
    image: "https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=600&h=400",
    category: "Breakfast",
    tags: ["pancakes", "breakfast", "apples", "cinnamon", "sweet", "family"],
    ingredients: [
      "2 cups all-purpose flour",
      "2 tbsp sugar",
      "2 tsp baking powder",
      "1 tsp ground cinnamon",
      "1/2 tsp salt",
      "2 large eggs",
      "1 3/4 cups milk",
      "1/4 cup melted butter",
      "1 tsp vanilla extract",
      "2 large apples, peeled and diced",
      "2 tbsp butter for apples",
      "3 tbsp brown sugar",
      "1/2 tsp cinnamon for apples",
      "Maple syrup for serving",
      "Butter for cooking"
    ],
    instructions: [
      "For caramelized apples: heat 2 tbsp butter in a large skillet over medium heat.",
      "Add diced apples, brown sugar, and 1/2 tsp cinnamon. Cook for 8-10 minutes until apples are tender and caramelized. Set aside.",
      "In a large bowl, whisk together flour, sugar, baking powder, cinnamon, and salt.",
      "In another bowl, whisk eggs, then add milk, melted butter, and vanilla extract.",
      "Pour wet ingredients into dry ingredients and stir just until combined. Don't overmix - lumps are okay.",
      "Heat a griddle or large skillet over medium heat. Lightly butter the surface.",
      "Pour 1/4 cup batter for each pancake onto the hot griddle.",
      "Cook until bubbles form on surface and edges look set, about 2-3 minutes.",
      "Flip and cook until golden brown on the other side, about 1-2 minutes more.",
      "Serve pancakes hot, topped with caramelized apples and maple syrup. Add a pat of butter if desired."
    ]
  },
  {
    id: 13,
    name: "Caprese Stuffed Chicken",
    description: "Juicy chicken breast stuffed with mozzarella, tomatoes, and fresh basil",
    difficulty: "Medium",
    rating: 4.6,
    prepTime: "35 min",
    servings: 4,
    image: "https://images.pexels.com/photos/106343/pexels-photo-106343.jpeg?auto=compress&cs=tinysrgb&w=600&h=400",
    category: "Italian",
    tags: ["chicken", "italian", "mozzarella", "tomatoes", "basil", "stuffed"],
    ingredients: [
      "4 boneless chicken breasts (200g each)",
      "200g fresh mozzarella, sliced",
      "2 large tomatoes, sliced",
      "1/4 cup fresh basil leaves",
      "2 tbsp balsamic glaze",
      "3 tbsp olive oil",
      "2 cloves garlic, minced",
      "1 tsp Italian seasoning",
      "Salt and black pepper to taste",
      "Toothpicks for securing",
      "2 tbsp butter",
      "1/4 cup chicken broth"
    ],
    instructions: [
      "Preheat oven to 200°C (400°F). Pat chicken breasts dry and season with salt and pepper.",
      "Using a sharp knife, cut a horizontal pocket in each chicken breast, being careful not to cut all the way through.",
      "Stuff each pocket with mozzarella slices, tomato slices, and basil leaves. Don't overstuff.",
      "Secure openings with toothpicks to prevent filling from falling out during cooking.",
      "Season outside of chicken with Italian seasoning, salt, and pepper.",
      "Heat olive oil in a large oven-safe skillet over medium-high heat.",
      "Add stuffed chicken breasts and sear for 3-4 minutes per side until golden brown.",
      "Add minced garlic to the pan and cook for 30 seconds until fragrant.",
      "Add butter and chicken broth to the pan, then transfer to preheated oven.",
      "Bake for 15-20 minutes until chicken reaches internal temperature of 74°C (165°F).",
      "Remove toothpicks, drizzle with balsamic glaze, and let rest for 5 minutes before slicing and serving."
    ]
  },
  {
    id: 14,
    name: "Vegetable Stir Fry",
    description: "Colorful mix of fresh vegetables stir-fried with ginger, garlic, and soy sauce",
    difficulty: "Easy",
    rating: 4.4,
    prepTime: "15 min",
    servings: 4,
    image: "https://images.pexels.com/photos/1640771/pexels-photo-1640771.jpeg?auto=compress&cs=tinysrgb&w=600&h=400",
    category: "Asian",
    tags: ["stir-fry", "vegetables", "asian", "healthy", "quick", "vegan"],
    ingredients: [
      "2 tbsp vegetable oil",
      "1 red bell pepper, sliced",
      "1 yellow bell pepper, sliced",
      "200g broccoli florets",
      "1 large carrot, julienned",
      "200g snap peas, trimmed",
      "1 zucchini, sliced",
      "3 cloves garlic, minced",
      "2 tbsp fresh ginger, minced",
      "3 tbsp soy sauce",
      "1 tbsp oyster sauce (or vegetarian alternative)",
      "1 tsp sesame oil",
      "1 tsp cornstarch",
      "2 tbsp water",
      "2 green onions, sliced",
      "1 tbsp sesame seeds",
      "Cooked rice for serving"
    ],
    instructions: [
      "Prepare all vegetables before starting to cook - slice peppers, cut broccoli into florets, julienne carrot, trim snap peas, and slice zucchini.",
      "In a small bowl, whisk together soy sauce, oyster sauce, sesame oil, cornstarch, and water to make the sauce.",
      "Heat vegetable oil in a large wok or skillet over high heat until smoking.",
      "Add broccoli and carrot first (they take longest to cook). Stir-fry for 2 minutes.",
      "Add bell peppers and continue stir-frying for 2 minutes.",
      "Add snap peas and zucchini. Stir-fry for 1-2 minutes until all vegetables are tender-crisp.",
      "Push vegetables to one side of wok. Add minced garlic and ginger to empty space and stir-fry for 30 seconds until fragrant.",
      "Mix garlic and ginger with vegetables, then pour sauce over everything.",
      "Stir-fry for 1-2 minutes until sauce thickens and coats all vegetables.",
      "Remove from heat, garnish with sliced green onions and sesame seeds. Serve immediately over steamed rice."
    ]
  },
  {
    id: 15,
    name: "Banana Bread",
    description: "Moist and flavorful banana bread with walnuts and a hint of vanilla",
    difficulty: "Easy",
    rating: 4.8,
    prepTime: "15 min prep, 60 min bake",
    servings: 8,
    image: "https://images.pexels.com/photos/830894/pexels-photo-830894.jpeg?auto=compress&cs=tinysrgb&w=600&h=400",
    category: "Dessert",
    tags: ["banana", "bread", "baking", "sweet", "breakfast", "snack"],
    ingredients: [
      "3 very ripe bananas, mashed",
      "1/3 cup melted butter",
      "3/4 cup sugar (or 1/2 cup for less sweet)",
      "1 large egg, beaten",
      "1 tsp vanilla extract",
      "1 tsp baking soda",
      "Pinch of salt",
      "1 1/2 cups all-purpose flour",
      "1/2 cup chopped walnuts (optional)",
      "1 tsp ground cinnamon",
      "Butter for greasing pan"
    ],
    instructions: [
      "Preheat oven to 175°C (350°F). Grease a 9x5 inch loaf pan with butter.",
      "In a large mixing bowl, mash ripe bananas with a fork until mostly smooth - a few small lumps are fine.",
      "Stir melted butter into mashed bananas until well combined.",
      "Mix in sugar, beaten egg, and vanilla extract until smooth.",
      "Sprinkle baking soda and salt over the mixture and stir to combine.",
      "Add flour and cinnamon, stirring just until flour disappears. Don't overmix or bread will be tough.",
      "Fold in chopped walnuts if using.",
      "Pour batter into prepared loaf pan and smooth the top.",
      "Bake for 55-65 minutes until a toothpick inserted in center comes out clean or with just a few moist crumbs.",
      "Cool in pan for 10 minutes, then turn out onto wire rack to cool completely before slicing. Store covered for up to 1 week."
    ]
  }
];