apiVersion: apps/v1
kind: Deployment
metadata:
  name: devdishes-backend
  labels:
    app: devdishes-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devdishes-backend
  template:
    metadata:
      labels:
        app: devdishes-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: {{ .Values.backend.env.DB_HOST | quote }}
            - name: DB_PORT
              value: {{ .Values.backend.env.DB_PORT | quote }}
            - name: DB_NAME
              value: {{ .Values.backend.env.DB_NAME | quote }}
            - name: DB_USER
              value: {{ .Values.backend.env.DB_USER | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.env.DB_PASSWORD_SECRET_NAME | quote }}
                  key: {{ .Values.backend.env.DB_PASSWORD_SECRET_KEY | quote }} 