name: CI/CD with Helm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

      # Detect changes and bump version for backend
      - name: Detect backend changes and bump version
        id: backend_version
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^backend/'; then
            version=$(cat backend/version.vars | grep tag | aw
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}k '{print $2}')
            version=$((version+1))
            echo $version > backend/.next_version
            echo "BACKEND_CHANGED=true" >> $GITHUB_ENV
            echo "BACKEND_VERSION=$version" >> $GITHUB_ENV
          else
            echo "BACKEND_CHANGED=false" >> $GITHUB_ENV
            echo "BACKEND_VERSION=$(cat backend/version.vars | grep tag | awk '{print $2}')" >> $GITHUB_ENV
          fi

      # Detect changes and bump version for frontend
      - name: Detect frontend changes and bump version
        id: frontend_version
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^frontend/'; then
            version=$(cat frontend/version.vars | grep tag | awk '{print $2}')
            version=$((version+1))
            echo $version > frontend/.next_version
            echo "FRONTEND_CHANGED=true" >> $GITHUB_ENV
            echo "FRONTEND_VERSION=$version" >> $GITHUB_ENV
          else
            echo "FRONTEND_CHANGED=false" >> $GITHUB_ENV
            echo "FRONTEND_VERSION=$(cat frontend/version.vars | grep tag | awk '{print $2}')" >> $GITHUB_ENV
          fi

      # Detect changes and bump version for db
      - name: Detect db changes and bump version
        id: db_version
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^devops/db/'; then
            version=$(cat devops/db/version.vars | grep tag | awk '{print $2}')
            version=$((version+1))
            echo $version > devops/db/.next_version
            echo "DB_CHANGED=true" >> $GITHUB_ENV
            echo "DB_VERSION=$version" >> $GITHUB_ENV
          else
            echo "DB_CHANGED=false" >> $GITHUB_ENV
            echo "DB_VERSION=$(cat devops/db/version.vars | grep tag | awk '{print $2}')" >> $GITHUB_ENV
          fi

      # Run backend unit tests if changed
      - name: Run backend unit tests
        if: env.BACKEND_CHANGED == 'true'
        run: |
          cd backend
          # Add your backend test command here, e.g. pytest or python -m unittest
          echo "No backend tests defined"

      # Run frontend unit tests if changed
      - name: Run frontend unit tests
        if: env.FRONTEND_CHANGED == 'true'
        run: |
          cd frontend
          npm install
          npm run test -- --passWithNoTests

      # Run db unit tests if changed
      - name: Run db unit tests
        if: env.DB_CHANGED == 'true'
        run: |
          cd devops/db
          # Add your db test command here
          echo "No db tests defined"

      # Build and push backend image if changed
      - name: Build and push backend image
        if: env.BACKEND_CHANGED == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./devops/backend/backend.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devdishes-backend:${{ env.BACKEND_VERSION }}
      - name: Update backend version.vars
        if: env.BACKEND_CHANGED == 'true'
        run: |
          echo "image: ${{ secrets.DOCKERHUB_USERNAME }}/devdishes-backend" > backend/version.vars
          echo "tag: ${{ env.BACKEND_VERSION }}" >> backend/version.vars

      # Build and push frontend image if changed
      - name: Build and push frontend image
        if: env.FRONTEND_CHANGED == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./devops/frontend/frontend.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devdishes-frontend:${{ env.FRONTEND_VERSION }}
      - name: Update frontend version.vars
        if: env.FRONTEND_CHANGED == 'true'
        run: |
          echo "image: ${{ secrets.DOCKERHUB_USERNAME }}/devdishes-frontend" > frontend/version.vars
          echo "tag: ${{ env.FRONTEND_VERSION }}" >> frontend/version.vars

      # Build and push db image if changed
      - name: Build and push db image
        if: env.DB_CHANGED == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./devops/db
          file: ./devops/db/db.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devdishes-db:${{ env.DB_VERSION }}
      - name: Update db version.vars
        if: env.DB_CHANGED == 'true'
        run: |
          echo "image: ${{ secrets.DOCKERHUB_USERNAME }}/devdishes-db" > devops/db/version.vars
          echo "tag: ${{ env.DB_VERSION }}" >> devops/db/version.vars

      # Commit and push version.vars changes if any
      - name: Commit and push version.vars
        if: env.BACKEND_CHANGED == 'true' || env.FRONTEND_CHANGED == 'true' || env.DB_CHANGED == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add backend/version.vars frontend/version.vars devops/db/version.vars
          git commit -m "ci: update version.vars for new image tags [skip ci]" || echo "No changes to commit"
          git push 
  publish-helm-chart:
    needs: build-and-deploy
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3

      - name: Package Helm chart
        run: |
          helm package devops/helm --destination chart-out
          helm repo index chart-out --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

      - name: Publish Helm chart to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./chart-out
          publish_branch: gh-pages 